import bcrypt from 'bcryptjs';
const data = {
  users: [
    {
      name: 'John',
      email: 'admin@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: true,
    },
    {
      name: 'Jane',
      email: 'user@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: 'Almonds',
      slug: 'Almonds',
      category: 'Nuts',
      image: '/images/Almonds.webp',
      isFeatured: true,
      featuredImage: '/images/Almonds_banner2.jpg',
      price: 10,
      brand: 'Nutlets',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'Almonds',
    },
    {
      name: 'Cashews',
      slug: 'Cashews',
      category: 'Nuts',
      image: '/images/Cashews_banner.png',
      isFeatured: true,
      featuredImage: '/images/Cashews_banner2.jpg',
      price: 12,
      brand: 'Nutlets',
      rating: 4.2,
      numReviews: 10,
      countInStock: 20,
      description: 'Cashews',
    },
    {
      name: 'Peanuts',
      slug: 'Peanuts',
      category: 'Nuts',
      image: '/images/peanuts.webp',
      price: 10,
      brand: 'Nutlets',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'Peanuts',
    },
    {
      name: 'Pistachio',
      slug: 'Pistachio',
      category: 'Nuts',
      image: '/images/pistachio.jpg',
      price: 14,
      brand: 'Nutlets',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'Pistachio',
    },
    {
      name: 'Walnuts',
      slug: 'Walnuts',
      category: 'Nuts',
      image: '/images/walnuts.jpg',
      price: 15,
      brand: 'Nutlets',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'Walnuts',
    },
    {
      name: 'Mix Nuts',
      slug: 'Mix-nuts',
      category: 'Nuts',
      image: '/images/mix_nuts.jpg',
      price: 18,
      brand: 'Nutlets',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'Mix Nuts',
    },
  ],
};
export default data;
